[package]
name = "lb-cli"
description = "Command line tools: config, replay, navigation, BSP, ABI"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
lb-core.workspace = true
lb-config.workspace = true
lb-bsp.workspace = true
lb-nav.workspace = true
lb-navgen.workspace = true
lb-mapknow.workspace = true
lb-game.workspace = true
lb-nav-api.workspace = true
lb-kin.workspace = true
lb-ffi.workspace = true
anyhow.workspace = true
lb-worldq.workspace = true
lb-runtime.workspace = true
lb-testkit.workspace = true
serde_json.workspace = true

[lints]
workspace = true
