/* lambdabots C ABI types. GENERATED by `cargo xtask abi` from crates/lb-ffi. Do not edit. */

#ifndef LAMBDABOTS_LB_ABI_H
#define LAMBDABOTS_LB_ABI_H

#include <stdint.h>
#include <stddef.h>

// Bumped on any incompatible change of this file.
#define LB_ABI_VERSION 1

#define LB_OK 0

#define LB_ERR_INVALID -1

#define LB_ERR_ABI -2

#define LB_ERR_STALE -3

#define LB_ERR_FULL -4

#define LB_ERR_REJECTED -5

#define LB_ERR_UNSUPPORTED -6

#define LB_ERR_NOT_FOUND -7

#define LB_ERR_BUSY -8

#define LB_PLATFORM_LINUX 1

#define LB_PLATFORM_WINDOWS 2

#define LB_PLATFORM_MACOS 3

#define LB_ENGINE_HLDS 1

#define LB_ENGINE_REHLDS 2

#define LB_ENGINE_XASH 3

#define LB_SHUTDOWN_DETACH 1

#define LB_SHUTDOWN_PROCESS_EXIT 2

#define LB_SHUTDOWN_FATAL 3

// Frame header flags.
#define LB_FRAME_PRE 1

#define LB_FRAME_POST 2

#define LB_FRAME_PAUSED 4

#define LB_FRAME_FIRST 8

// Client slot states.
#define LB_CLIENT_FREE 0

#define LB_CLIENT_CONNECTING 1

#define LB_CLIENT_CONNECTED 2

#define LB_CLIENT_SPAWNED 3

// Channel availability bits reported in [`LbCompatFacts::channels`].
#define LB_CH_SV_STARTSOUND 1

#define LB_CH_MSGMGR 2

#define LB_CH_EMITPINGS 4

#define LB_CH_DROPCLIENT 8

#define LB_CH_HOSTTIME 16

#define LB_CH_HOOK_TABLES 32

#define LB_CH_AMBIENT_SOUND 64

#define LB_CH_PLAYBACK_EVENT 128

// Indices into [`LbInitInfo::sizes`].
#define LB_SZ_INIT_INFO 0

#define LB_SZ_MAP_INFO 1

#define LB_SZ_FRAME_HEADER 2

#define LB_SZ_FRAME_INPUT 3

#define LB_SZ_CLIENT_SNAPSHOT 4

#define LB_SZ_SELF_SNAPSHOT 5

#define LB_SZ_EVENT_HEADER 6

#define LB_SZ_BOT_COMMAND 7

#define LB_SZ_MOVE_FEEDBACK 8

#define LB_SZ_CLIENT_COMMAND 9

#define LB_SZ_TRACE_REQUEST 10

#define LB_SZ_TRACE_RESULT 11

#define LB_SZ_ENTITY_SNAPSHOT 12

#define LB_SZ_TRACK_RULE 13

#define LB_SZ_CREATE_BOT_REQUEST 14

#define LB_SZ_CREATE_BOT_RESULT 15

#define LB_SZ_DEBUG_PRIM 16

#define LB_SZ_CVAR_SPEC 17

#define LB_SZ_COMPAT_FACTS 18

#define LB_SZ_HOST_API 19

#define LB_SZ_MSG_ARG 20

#define LB_SZ_DISGUISE 21

#define LB_SZ_COUNT 24

#define LB_EV_CLIENT 1

#define LB_EV_USER_MSG 2

#define LB_EV_SOUND 3

#define LB_EV_PLAYBACK 4

#define LB_EV_ENTITY 5

#define LB_EV_CLIENT_CMD 6

#define LB_EV_SERVER_CMD 7

#define LB_EV_FIXANGLE 8

#define LB_EV_STRING 9

#define LB_EV_REG_MSG 10

#define LB_EV_PRECACHE_EVENT 11

#define LB_EV_LOG 12

#define LB_EV_OVERFLOW 13

// Context in which a record was captured.
#define LB_CTX_FRAME 0

#define LB_CTX_BOTCMD 1

#define LB_CTX_BOTCLCMD 2

#define LB_CTX_GAMEDLL 3

#define LB_CTX_CORE 4

#define LB_CLIENT_EV_CONNECT 1

#define LB_CLIENT_EV_CONNECT_REJECTED 2

#define LB_CLIENT_EV_PUT_IN_SERVER 3

#define LB_CLIENT_EV_DISCONNECT 4

#define LB_CLIENT_EV_INFO 5

#define LB_MSG_ARG_BYTE 1

#define LB_MSG_ARG_CHAR 2

#define LB_MSG_ARG_SHORT 3

#define LB_MSG_ARG_LONG 4

#define LB_MSG_ARG_ANGLE 5

#define LB_MSG_ARG_COORD 6

#define LB_MSG_ARG_STRING 7

#define LB_MSG_ARG_ENTITY 8

#define LB_MSG_FLAG_HAS_ORIGIN 1

#define LB_MSG_FLAG_TRUNCATED 2

#define LB_MSG_FLAG_FROM_MSGMGR 4

#define LB_SOUND_SRC_EMIT 1

#define LB_SOUND_SRC_AMBIENT 2

#define LB_SOUND_SRC_REHLDS 3

#define LB_ENTITY_EV_SPAWN 1

#define LB_ENTITY_EV_FREE 2

#define LB_CMD_SET_SEED 1

#define LB_MOVE_OK 0

#define LB_MOVE_STALE 1

#define LB_MOVE_NOT_OURS 2

#define LB_MAX_CLIENT_CMD_ARGS 8

#define LB_TRACE_LINE 1

#define LB_TRACE_HULL 2

#define LB_TRACE_MODEL 3

#define LB_TRACE_IGNORE_MONSTERS 1

#define LB_TRACE_IGNORE_GLASS 2

#define LB_TRACE_MISSILE 4

// Hull numbers as used by the engine: 0 point, 1 standing player, 2 large, 3 crouching player.
#define LB_HULL_POINT 0

#define LB_HULL_HUMAN 1

#define LB_HULL_LARGE 2

#define LB_HULL_HEAD 3

#define LB_TRACK_EXACT 1

#define LB_TRACK_PREFIX 2

#define LB_DISGUISE_PING 1

#define LB_DISGUISE_AUTHID 2

#define LB_DISGUISE_SESSION 4

#define LB_DEBUG_LINE 1

#define LB_DEBUG_TEXT 2

#define LB_CVAR_PROTECTED 1

#define LB_CVAR_SERVER 2

#define LB_CVAR_READONLY 4

#define LB_PRINT_CONSOLE 1

#define LB_PRINT_CENTER 2

#define LB_PRINT_CHAT 3

// Borrowed bytes, not NUL-terminated, valid only for the duration of the call that received them.
typedef struct LbStr {
  const uint8_t *ptr;
  uint32_t len;
} LbStr;

typedef struct LbVec3 {
  float x;
  float y;
  float z;
} LbVec3;

// Entity reference validated by the adapter through the edict serial number. `index == 0` is the world.
typedef struct LbEntRef {
  uint16_t index;
  uint16_t pad;
  uint32_t serial;
} LbEntRef;

typedef struct LbArgs {
  uint32_t argc;
  uint32_t pad;
  const struct LbStr *argv;
  struct LbStr line;
} LbArgs;

typedef struct LbInitInfo {
  uint32_t struct_size;
  uint32_t abi_version;
  uint32_t sizes[LB_SZ_COUNT];
  struct LbStr adapter_version;
  struct LbStr plugin_path;
  struct LbStr game_dir;
  struct LbStr install_dir;
  uint8_t platform;
  uint8_t pointer_size;
  uint8_t late_load;
  uint8_t pad[5];
} LbInitInfo;

typedef struct LbInitResult {
  uint32_t struct_size;
  uint32_t abi_version;
  int32_t status;
  uint32_t pad;
  // Points to static memory owned by the core.
  struct LbStr core_version;
} LbInitResult;

typedef struct LbMapInfo {
  uint32_t struct_size;
  uint32_t map_epoch;
  struct LbStr map_name;
  struct LbStr bsp_path;
  uint32_t max_clients;
  uint32_t max_edicts;
  uint32_t worldmap_crc;
  uint8_t has_crc;
  uint8_t late_load;
  uint8_t pad[2];
} LbMapInfo;

typedef struct LbFrameHeader {
  uint32_t struct_size;
  uint32_t map_epoch;
  uint64_t frame_no;
  // Simulation time in seconds; double precision (the engine's `gpGlobals->time` is a float).
  double sim_time;
  double frame_time;
  uint64_t mono_ns;
  float engine_time;
  uint32_t flags;
  uint32_t max_clients;
  uint32_t num_edicts;
} LbFrameHeader;

// Raw per-slot client state. Sensor-only: no health, armor, weapons or buttons of other players.
typedef struct LbClientSnapshot {
  uint8_t slot;
  uint8_t state;
  uint8_t is_fake;
  uint8_t is_ours;
  int32_t userid;
  struct LbVec3 origin;
  struct LbVec3 velocity;
  // Model angles (what other players see).
  struct LbVec3 angles;
  struct LbVec3 view_ofs;
  struct LbVec3 mins;
  struct LbVec3 maxs;
  struct LbVec3 rendercolor;
  uint32_t flags;
  uint32_t effects;
  uint8_t movetype;
  uint8_t solid;
  uint8_t deadflag;
  uint8_t waterlevel;
  uint8_t rendermode;
  uint8_t renderfx;
  // `entvars.iStepLeft`, toggled by the player movement code on every footstep.
  uint8_t step_left;
  uint8_t pad0;
  float renderamt;
  float frame;
  float frags;
  int32_t sequence;
  int32_t gaitsequence;
  uint16_t weaponmodel_id;
  uint16_t model_id;
  uint16_t ping_ms;
  uint16_t pad1;
} LbClientSnapshot;

// State of one of our bots. Only our own bots are ever described by this struct.
typedef struct LbSelfSnapshot {
  uint8_t slot;
  uint8_t deadflag;
  uint8_t movetype;
  uint8_t waterlevel;
  uint32_t bot_gen;
  float health;
  float armor;
  uint32_t weapons_mask;
  float maxspeed;
  float fov;
  float duck_time;
  float fall_velocity;
  uint32_t flags;
  int32_t watertype;
  struct LbVec3 origin;
  struct LbVec3 velocity;
  struct LbVec3 v_angle;
  struct LbVec3 angles;
  struct LbVec3 punchangle;
  struct LbVec3 view_ofs;
  struct LbVec3 basevelocity;
  uint8_t in_duck;
  uint8_t has_longjump;
  uint8_t fixangle;
  uint8_t pad0;
  uint16_t groundentity;
  uint16_t buttons_applied;
  float frags;
  uint32_t pad1;
} LbSelfSnapshot;

// A batch of event records captured since the previous frame: `LbEventHeader` + payload, each
// record padded to a multiple of 8 bytes.
typedef struct LbEventBatch {
  const uint8_t *data;
  uint32_t len;
  uint32_t count;
  uint32_t dropped;
  uint32_t first_seq;
} LbEventBatch;

typedef struct LbFrameInput {
  uint32_t struct_size;
  uint32_t client_count;
  struct LbFrameHeader header;
  const struct LbClientSnapshot *clients;
  const struct LbSelfSnapshot *selves;
  uint32_t self_count;
  uint32_t pad;
  struct LbEventBatch events;
} LbFrameInput;

typedef struct LbEventHeader {
  uint16_t kind;
  // Total record size including this header, a multiple of 8.
  uint16_t size;
  uint32_t seq;
  // `LB_CTX_*` in the low byte, slot in the second byte for bot contexts.
  uint32_t ctx;
  uint32_t frame_no_low;
  double sim_time;
} LbEventHeader;

// Payload of `LB_EV_CLIENT`; followed by `name_len` bytes of name, `model_len` bytes of model,
// `addr_len` bytes of address (all without terminator).
typedef struct LbEvClient {
  uint8_t what;
  uint8_t slot;
  uint8_t is_ours;
  uint8_t is_fake;
  int32_t userid;
  uint32_t bot_gen;
  uint8_t topcolor;
  uint8_t bottomcolor;
  uint8_t name_len;
  uint8_t model_len;
  uint8_t addr_len;
  uint8_t pad[3];
  uint8_t auth_id_len;
  uint8_t pad2[3];
} LbEvClient;

// Payload of `LB_EV_USER_MSG`; followed by `argc` × [`LbMsgArg`] and then the string bytes
// referenced by `LbMsgArg::str_off`/`str_len` (offsets relative to the end of the argument array).
typedef struct LbEvUserMsg {
  int32_t msg_id;
  uint8_t dest;
  uint8_t target_slot;
  uint8_t flags;
  uint8_t argc;
  struct LbVec3 origin;
  uint16_t strings_len;
  uint16_t pad;
} LbEvUserMsg;

typedef struct LbMsgArg {
  uint8_t tag;
  uint8_t pad[3];
  int32_t ival;
  float fval;
  uint16_t str_off;
  uint16_t str_len;
} LbMsgArg;

// Payload of `LB_EV_SOUND`; followed by `sample_len` bytes of the sample name.
typedef struct LbEvSound {
  uint8_t source;
  uint8_t channel;
  uint16_t sample_len;
  struct LbEntRef entity;
  struct LbVec3 origin;
  float volume;
  float attenuation;
  int32_t flags;
  int32_t pitch;
} LbEvSound;

// Payload of `LB_EV_PLAYBACK` (client-predicted events such as weapon fire).
typedef struct LbEvPlayback {
  int32_t flags;
  uint16_t event_index;
  uint16_t pad;
  struct LbEntRef invoker;
  struct LbVec3 origin;
  struct LbVec3 angles;
  struct LbVec3 invoker_origin;
  float delay;
  float fparam1;
  float fparam2;
  int32_t iparam1;
  int32_t iparam2;
  int32_t bparam1;
  int32_t bparam2;
} LbEvPlayback;

// Payload of `LB_EV_ENTITY`.
typedef struct LbEvEntity {
  uint8_t what;
  uint8_t kind;
  uint16_t classname_id;
  struct LbEntRef ent;
  struct LbVec3 origin;
  uint32_t pad[2];
} LbEvEntity;

// Payload of `LB_EV_CLIENT_CMD` / `LB_EV_SERVER_CMD`; followed by `argc` × (u16 length + bytes),
// then `line_len` bytes of the full argument line.
typedef struct LbEvCommand {
  uint8_t slot;
  uint8_t argc;
  uint16_t line_len;
  int32_t userid;
} LbEvCommand;

// Payload of `LB_EV_FIXANGLE`: the adapter acknowledged a forced view angle for one of our bots.
typedef struct LbEvFixangle {
  uint8_t slot;
  uint8_t mode;
  uint16_t pad;
  uint32_t bot_gen;
  struct LbVec3 angles;
  uint32_t pad2;
} LbEvFixangle;

// Payload of `LB_EV_STRING` / `LB_EV_REG_MSG` / `LB_EV_PRECACHE_EVENT` / `LB_EV_LOG`; followed by
// `len` bytes.
typedef struct LbEvNamed {
  // String id, user message id, event index or log level depending on the record kind.
  int32_t id;
  uint16_t len;
  uint16_t extra;
} LbEvNamed;

// Payload of `LB_EV_OVERFLOW`.
typedef struct LbEvOverflow {
  uint32_t dropped_records;
  uint32_t dropped_bytes;
} LbEvOverflow;

typedef struct LbBotCommand {
  uint8_t slot;
  uint8_t flags;
  uint16_t buttons;
  uint32_t bot_gen;
  struct LbVec3 view_angles;
  float forwardmove;
  float sidemove;
  float upmove;
  uint8_t impulse;
  uint8_t msec;
  uint16_t pad;
  uint32_t random_seed;
} LbBotCommand;

typedef struct LbMoveFeedback {
  uint8_t slot;
  uint8_t status;
  uint8_t deadflag;
  uint8_t waterlevel;
  uint32_t flags;
  uint64_t frame_no;
  struct LbVec3 origin;
  struct LbVec3 velocity;
  struct LbVec3 v_angle;
  float health;
  uint8_t movetype;
  uint8_t pad[3];
  uint32_t pad2;
} LbMoveFeedback;

typedef struct LbClientCommand {
  uint8_t slot;
  uint8_t argc;
  uint16_t pad;
  uint32_t bot_gen;
  struct LbStr argv[LB_MAX_CLIENT_CMD_ARGS];
} LbClientCommand;

typedef struct LbTraceRequest {
  struct LbVec3 start;
  struct LbVec3 end;
  uint8_t kind;
  uint8_t hull;
  uint16_t flags;
  struct LbEntRef ignore;
  struct LbEntRef model;
  uint32_t pad;
} LbTraceRequest;

typedef struct LbTraceResult {
  float fraction;
  struct LbVec3 end_pos;
  struct LbVec3 plane_normal;
  float plane_dist;
  struct LbEntRef hit;
  int32_t hitgroup;
  uint8_t all_solid;
  uint8_t start_solid;
  uint8_t in_open;
  uint8_t in_water;
  uint8_t hit_rendermode;
  uint8_t hit_renderfx;
  uint8_t hit_solid;
  uint8_t pad;
  float hit_renderamt;
  uint16_t hit_classname_id;
  uint16_t pad2;
  uint32_t pad3;
} LbTraceResult;

// Entity kinds assigned by the track rules (values chosen by the core).
typedef struct LbTrackRule {
  struct LbStr pattern;
  uint8_t match_mode;
  uint8_t kind;
  uint8_t pad[6];
} LbTrackRule;

typedef struct LbEntitySnapshot {
  struct LbEntRef ent;
  struct LbEntRef owner;
  uint16_t classname_id;
  uint16_t model_id;
  uint8_t kind;
  uint8_t solid;
  uint8_t movetype;
  uint8_t rendermode;
  struct LbVec3 origin;
  struct LbVec3 angles;
  struct LbVec3 velocity;
  struct LbVec3 avelocity;
  struct LbVec3 absmin;
  struct LbVec3 absmax;
  struct LbVec3 rendercolor;
  uint32_t effects;
  uint32_t spawnflags;
  float frame;
  float renderamt;
  uint8_t renderfx;
  uint8_t deadflag;
  uint8_t pad[10];
} LbEntitySnapshot;

typedef struct LbKeyValue {
  struct LbStr key;
  struct LbStr value;
} LbKeyValue;

typedef struct LbCreateBotRequest {
  struct LbStr name;
  struct LbStr connect_addr;
  const struct LbKeyValue *infokeys;
  uint32_t infokey_count;
  uint32_t flags;
} LbCreateBotRequest;

typedef struct LbCreateBotResult {
  int32_t status;
  uint8_t slot;
  uint8_t pad[3];
  int32_t userid;
  uint32_t bot_gen;
  uint8_t reject_reason[128];
} LbCreateBotResult;

typedef struct LbDisguise {
  uint8_t slot;
  uint8_t flags;
  uint16_t ping;
  uint32_t bot_gen;
  uint8_t loss;
  uint8_t pad[3];
  float session_seconds;
  uint8_t authid[40];
} LbDisguise;

typedef struct LbDebugPrim {
  uint8_t kind;
  uint8_t r;
  uint8_t g;
  uint8_t b;
  uint8_t width;
  uint8_t life_ds;
  uint8_t brightness;
  uint8_t channel;
  struct LbVec3 a;
  struct LbVec3 b2;
  uint32_t pad;
  struct LbStr text;
} LbDebugPrim;

typedef struct LbCvarSpec {
  struct LbStr name;
  struct LbStr default_value;
  uint32_t flags;
  uint32_t pad;
} LbCvarSpec;

typedef struct LbOwnedBuffer {
  const uint8_t *ptr;
  uint32_t len;
  uint32_t pad;
  void *token;
} LbOwnedBuffer;

typedef struct LbCompatFacts {
  uint8_t engine_kind;
  uint8_t metamod_has_hook_tables;
  uint8_t rehlds_major;
  uint8_t rehlds_minor;
  int32_t rehlds_build;
  uint32_t channels;
  uint32_t pad;
  uint8_t engine_version[64];
  uint8_t metamod_version[32];
  uint8_t gamedll_desc[64];
  uint8_t gamedll_path[256];
} LbCompatFacts;

typedef struct LbHostApi {
  uint32_t struct_size;
  uint32_t abi_version;
  void *ctx;
  void (*server_print)(void *ctx, struct LbStr text);
  void (*client_print)(void *ctx, uint8_t slot, uint8_t where_, struct LbStr text);
  // Queued; executed by the engine after the current frame, never immediately.
  void (*server_command)(void *ctx, struct LbStr text);
  int32_t (*cvar_register)(void *ctx,
                           const struct LbCvarSpec *specs,
                           uint32_t count,
                           uint16_t *out_handles);
  uint16_t (*cvar_find)(void *ctx, struct LbStr name);
  float (*cvar_get_float)(void *ctx, uint16_t handle);
  uint32_t (*cvar_get_string)(void *ctx, uint16_t handle, uint8_t *buf, uint32_t cap);
  void (*cvar_set)(void *ctx, uint16_t handle, struct LbStr value);
  void (*trace)(void *ctx, const struct LbTraceRequest *req, struct LbTraceResult *out);
  uint32_t (*trace_batch)(void *ctx,
                          const struct LbTraceRequest *reqs,
                          struct LbTraceResult *out,
                          uint32_t count);
  int32_t (*point_contents)(void *ctx, struct LbVec3 point);
  int32_t (*registry_set_rules)(void *ctx, const struct LbTrackRule *rules, uint32_t count);
  uint32_t (*snapshot_entities)(void *ctx,
                                uint32_t kind_mask,
                                struct LbEntitySnapshot *out,
                                uint32_t cap);
  int32_t (*get_entity)(void *ctx, struct LbEntRef ent, struct LbEntitySnapshot *out);
  int32_t (*set_capture_mask)(void *ctx, const uint8_t *mask);
  int32_t (*resolve_user_msg)(void *ctx, struct LbStr name, int32_t *size);
  int32_t (*create_bot)(void *ctx,
                        const struct LbCreateBotRequest *req,
                        struct LbCreateBotResult *out);
  int32_t (*kick_bot)(void *ctx, uint8_t slot, uint32_t bot_gen, struct LbStr reason);
  int32_t (*bot_client_commands)(void *ctx, const struct LbClientCommand *cmds, uint32_t count);
  int32_t (*run_player_moves)(void *ctx,
                              const struct LbBotCommand *cmds,
                              uint32_t count,
                              struct LbMoveFeedback *feedback);
  uint32_t (*get_physics_key)(void *ctx, uint8_t slot, struct LbStr key, uint8_t *buf, uint32_t cap);
  uint32_t (*get_client_info_key)(void *ctx,
                                  uint8_t slot,
                                  struct LbStr key,
                                  uint8_t *buf,
                                  uint32_t cap);
  int32_t (*get_weapon_data)(void *ctx, uint8_t slot, void *out, uint32_t cap);
  int32_t (*set_bot_disguise)(void *ctx, const struct LbDisguise *d);
  int32_t (*get_player_stats)(void *ctx, uint8_t slot, int32_t *ping, int32_t *loss);
  int32_t (*load_file)(void *ctx, struct LbStr path, struct LbOwnedBuffer *out);
  void (*free_file)(void *ctx, struct LbOwnedBuffer *buf);
  int32_t (*send_debug)(void *ctx, uint8_t slot, const struct LbDebugPrim *prims, uint32_t count);
  int32_t (*get_compat_facts)(void *ctx, struct LbCompatFacts *out);
} LbHostApi;

#endif  /* LAMBDABOTS_LB_ABI_H */
