/* lambdabots core entry points. GENERATED by `cargo xtask abi` from crates/lb-plugin. Do not edit. */

#ifndef LAMBDABOTS_LB_CORE_H
#define LAMBDABOTS_LB_CORE_H

#include "lb_abi.h"

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Initializes the core. Returns `LB_OK` or an error status; `result` is always filled.
//
// # Safety
// Called by the adapter on the engine main thread with valid pointers.
int32_t lb_core_init(const LbHostApi *host, const LbInitInfo *info, LbInitResult *result);

void lb_core_shutdown(uint32_t reason);

// # Safety
// `info` must be valid during the call.
void lb_core_map_start(const LbMapInfo *info);

void lb_core_map_end(uint32_t _epoch);

// # Safety
// `input` and everything it points to must be valid during the call.
void lb_core_frame_pre(const LbFrameInput *input);

// # Safety
// `input` must be valid during the call.
void lb_core_frame_post(const LbFrameInput *input);

// # Safety
// `args` must be valid during the call.
void lb_core_server_command(const LbArgs *args);

void lb_core_fatal(LbStr message);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* LAMBDABOTS_LB_CORE_H */
